### PR TITLE
General cleanup + add Puppet4 datatypes

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
How does this relate to https://github.com/camptocamp/puppet-systemd/pull/18?

**Comment by bastelfreak** [comment]
Shiiiiit I mised #18 :(
We should probably integrate both. I'm fine with dropping my puppet4 commit here.

**Comment by EmilienM** [comment]
it would be really great to merge that PR, one day.

**Comment by mmerfort** [comment]
A forge release after this has been merged would also be great.

**Comment by trevor-vaughan** [comment]
@bastelfreak #18 has been merged if you want to rebase and/or see if you have anything that needs to be changed that should be in this PR.

**Pull request merged**
