### PR TITLE
Add loginctl_user type/provider

### PR DESCRIPTION
**Pull request by raphink**
Example usage:

```puppet
loginctl_user { 'foo':
  linger => enabled,
}
```

### CODE REVIEW

**Comment by bastelfreak** [comment]
@raphink should this be documented in the README.md?

**Comment by raphink** [comment]
Actually, before we release 2.8.0, I'm wondering if this is the right interface for the type. Maybe this would be better:

```puppet
user_linger { 'foo':
  ensure => enabled,
```

It makes the type ensurable and removes the implementation (`loginctl`) from the type.

What do you think @bastelfreak, @mcanevet?

**Comment by bastelfreak** [comment]
From a user point of view I think both ways are. The implementation for your `user_linger` example might be easier. Another idea I had is that another parameter to the user core type would be nice. but getting stuff into puppet core takes a long time...

**Comment by trevor-vaughan** [comment]
Given how many users/resources there may be on a given system, you may want to have a Hash interface that only creates one resource to prevent death by 10k resources. Probably future work, but something to keep in mind before this completely goes down the `file_line`/augeas rabbit hole.

**Comment by raphink** [comment]
Yes, the core type was an option, too. That would require adding a new feature also. It is probably possible to provide this as a plugin with some monkey patching... but supporting that on the long run might not be fun... and does it make sense to implement linger for all OSes?

**Comment by trevor-vaughan** [comment]
Looking at the options a bit more, I would prefer the current implementation since it reduces system resources. Technically, you could implement both and make them conflict with each other but that may be too much work.

**Comment by raphink** [comment]
@trevor-vaughan why does it reduce system resources?

**Comment by trevor-vaughan** [comment]
@raphink Because `loginctl_user` is one resource with many future options whereas `user_linger` is one resource per option. In the OO model, the user is the object and `linger` is the attribute. If you start modeling based on attributes, it explodes quickly.

I still think it's a horrible idea to support different daemons with different versions in the same module, but I lost that fight a while ago.

**Comment by raphink** [comment]
Good point... so let's keep it the way it is then. I'll cut the release tomorrow I think.

**Pull request merged**
