### PR TITLE
Add ability to specify supported option 'infinity' for LimitNPROC

### PR DESCRIPTION
**Pull request by hdeheer**
From `limits.conf(5)`
All items support the values _-1_, _unlimited_ or _infinity_ indicating no limit, except for priority and nice.

### CODE REVIEW

**Comment by raphink** [comment]
Thanks for that. Why not use the other, more complete, regexp as the other fields then?

**Comment by hdeheer** [comment]
@raphink I changed the validation as per your recommendation.

**Comment by hdeheer** [comment]
@raphink a friendly reminder. I changed the validation as per your recommendation.

**Comment by hdeheer** [comment]
Solves #173

**Pull request merged**
