### PR TITLE
Use the correct type on $service_limits

### PR DESCRIPTION
**Pull request by ekohl**
Closes GH-49

### CODE REVIEW

**Comment by raphink** [comment]
Why not adapt `Systemd::ServiceLimits` instead?

**Comment by ekohl** [comment]
This calls create_resources on the ```systemd::service_limits``` defined type. That has a parameter ```limits``` with the ```Systemd::ServiceLimits``` which does the actual checks.

**Comment by raphink** [comment]
Ah, that makes sense. LGTM then.

**Comment by bastelfreak** [comment]
Thanks for the PR @ekohl

**Comment by ekohl** [comment]
@bastelfreak I'd say this is a bugfix rather than an enhancement. Before the parameter was unusable.

**Pull request merged**
